name: Deploy to ECR

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: us-east-1
      ECR_REPOSITORY_MYSQL: dharmik-mysql-repo
      ECR_REPOSITORY_APP: dharmikwebapp
      IMAGE_TAG: v1.0

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push mysql image to Amazon ECR
      run: |
        
        docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_MYSQL }}:${{ env.IMAGE_TAG }} -f Dockerfile_mysql .
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_MYSQL }}:${{ env.IMAGE_TAG }}
        
    - name: Build, tag, and push app image to Amazon ECR
      run: |
        
        docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_APP }}:${{ env.IMAGE_TAG }} -f Dockerfile .
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_APP }}:${{ env.IMAGE_TAG }}
